### PR TITLE
FE-1227 - Changes default branch from "master" to "main"

### PR DESCRIPTION
**Pull request by nicklemmon**
Part of [FE-1227](https://sparkpost.atlassian.net/browse/FE-1227)

### What Changed

- Updates CodeQL analysis config to target the `main` branch vs. the `master` branch as a basis of comparison

### How To Test

- Ensure any references to the `master` branch in the repo are replaced with `main`

### CODE REVIEW

**Review by nstanard — APPROVED** [review]
I did a quick search through the repo to try to find any other references and didn't come up with anything - this lgtm!

Like you said, we'll have to make this happen eventually no matter what. Remind me - what's the plan for after we merge this? Everybody else will simply have to update their PR base branch? Anything else? I remember on a call recently you threw out a few steps for how to handle the merge/update - can you put those steps on this PR too for historical purposes and for me while we release and make this change?

My current thought. (but please post yours in the description)
1. Merge this into master.
2. Use GitHub to change the default branch to main.
3. Update AWS code pipeline?
4. ? Profit ? 


I don't see where in AWS we update the branch - does that happen on it's own when we tell GH our default branch is main instead of master?
image

**Comment by nstanard** [comment]
Update: I saw this come through after making my other comment: https://sparkpost.atlassian.net/wiki/spaces/ENG/pages/976158888/How+to+change+default+Github+branch+in+AWS+CodePipeline?src=mail&src.mail.timestamp=1616536238388&src.mail.notification=com.atlassian.confluence.plugins.confluence-content-notifications-plugin%3Apage-created-notification&src.mail.recipient=8a7f808973c999c40173caeff92703b4&src.mail.action=view

🎊 - I do think we should lay out our plan in steps on this PR though.

**Comment by nicklemmon** [comment]
> Update: I saw this come through in an email after making my other comment: https://sparkpost.atlassian.net/wiki/spaces/ENG/pages/976158888/How+to+change+default+Github+branch+in+AWS+CodePipeline?src=mail&src.mail.timestamp=1616536238388&src.mail.notification=com.atlassian.confluence.plugins.confluence-content-notifications-plugin%3Apage-created-notification&src.mail.recipient=8a7f808973c999c40173caeff92703b4&src.mail.action=view
> 
> 🎊 - I do think we should lay out our plan in steps on this PR though.

Cool! I definitely had not seen this doc.

Relevant Slack thread with our proposed strategy for FE specifically: [Slack Thread](https://msys.slack.com/archives/GKXTKHDSP/p1616002315013800)

**Comment by nicklemmon** [comment]
@nstanard - this one needs a review as well for this ticket! https://github.com/SparkPost/ux-cloudformation/pull/25

**Comment by nstanard** [comment]
I think it might be good to plan this for first thing Monday morning so we can get through it and deal with any unknowns that might come up. I would still like to see the steps/plan converted from Slack over to the description of the PR.

**Comment by nicklemmon** [comment]
> I think it might be good to plan this for first thing Monday morning so we can get through it and deal with any unknowns that might come up. I would still like to see the steps/plan converted from Slack over to the description of the PR.

Maybe in the Jira ticket? Since most of the steps are outside of GitHub.

**Comment by nstanard** [comment]
> I'll be out on Monday as well - how would you feel about trying this tomorrow morning?

If the rest of FE is comfortable with making this happen this morning I'm game.

**Pull request merged**
