### PR TITLE
FE-1346 Replace 'master account' with 'primary account'

### PR DESCRIPTION
**Pull request by jonambas**
### What Changed
- Replaces `master account` strings with `primary account`.
- 
### How To Test
- Run and verify unit and integration tests
- Verify the following:
  -  The `Subaccount` label component
  -  The `SubaccountSection` component
  - Can be verified via the following:
    - AB test create subaccount field help text
    - Suppression create subaccount field help text
    - Suppression upload subaccount field help text
    - Suppression table entry assigned to primary account
    - Domains create page subaccount radio group
    - Data privacy page subaccount options
    - Report builder & summary report group by table with a primary account row
    - Signals (HS, Spam Traps, Eng) table cells with a primary account row
    - Signals (HS, Spam Traps, Eng) table subaccount filter
    - Webhooks create subaccount radio group
    - Webhook entry assigned to primary account and primary and all

### To Do

- [ ] Any outstanding tasks go here

### CODE REVIEW

**Review by shrirupa — COMMENTED** [review]
Screen Shot 2021-01-21 at 3 13 57 PM
pages/signals/components/filters/SubaccountFilter.js has "Master and all Subaccounts"

**Comment by shrirupa** [comment]
nit pick - few places in test.js has `master` in test description

**Comment by jonambas** [comment]
Getting a failing test on the Events page share modal – not sure if I did something to break it

**Review by shrirupa — APPROVED** [review]
Looks good to me!

**Review by shrirupa — COMMENTED** [review]
sorry for this, few remanants of master in tests of src/selectors and EngagementRecencyOverview.test, HealthScoreOverview.test and SpamTrapOverview.test

**Comment by jonambas** [comment]
@shrirupa no worries! thanks for catching

**Review by shrirupa — APPROVED** [review]

**Pull request merged**
