### PR TITLE
FE-696 - Remove docs files stored in the repo, migrate to wiki

### PR DESCRIPTION
**Pull request by nicklemmon**
[FE-696](https://jira.int.messagesystems.com/browse/FE-696)

### What Changed
* Removed `.md` files from the `docs` directory in the repo
* Migrated content to the wiki
* Added Fast and Furious gif to Wiki footer to appear on every page
* Added inspirational quote from Dominic Toretto

### How To Test
* Look through the [wiki](https://github.com/SparkPost/2web2ui/wiki) and check for any missing content
* Verify duplicated content was deleted

### To Do
- [x] Incorporate feedback

### CODE REVIEW

**Comment by PatrickSison** [comment]
Feature flags documentation I believe is missing from wiki (which is fine). It should probably live in [internal docs](https://confluence.int.messagesystems.com/display/ENG/FE%3A+Feature+Flagshttps://confluence.int.messagesystems.com/display/ENG/FE%3A+Feature+Flags)

**Comment by nicklemmon** [comment]
> Feature flags documentation I believe is missing from wiki (which is fine). It should probably live in [internal docs](https://confluence.int.messagesystems.com/display/ENG/FE%3A+Feature+Flagshttps://confluence.int.messagesystems.com/display/ENG/FE%3A+Feature+Flags)

Definitely! Brian noticed that too. I updated the title.

**Comment by PatrickSison** [comment]
Definitely. Moved the how to enable/disable a flag to confluence, but maybe the rest can exist within the wiki?

**Comment by nicklemmon** [comment]
> Definitely. Moved the how to enable/disable a flag to confluence, but maybe the rest can exist within the wiki?

I think that makes sense. I fixed another reference to the feature flags that I didn't catch earlier. Should be good for you to approve? I can merge after.

Thanks!

**Pull request closed without merging**
